apiVersion: apps/v1
kind: Deployment
metadata:
  name: std_app-Deployment
  lables:
    app:std_app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: std_app
  template:
    metadata:
      labels:
        app:std_app
    spec:
      containers:
        - name: std_app
          image: shimpy12/studentassignment1
          ports:
          - containerPort: 5000